[phases.setup]
nixPkgs = ['nodejs_22', 'ffmpeg', 'pnpm', 'python311']

[phases.build]
cmds = [
  'pnpm install --filter n8n --recursive'
]

[phases.start]
cmd = 'pnpm --filter n8n start'  # 👈 run from correct workspace
