[phases.setup]
nixPkgs = [
  "nodejs_22",
  "pnpm",
  "findutils"
]

cmds = [
  "curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz",
  "tar -xf ffmpeg.tar.xz",
  "FFMPEG_DIR=$(find . -type d -name 'ffmpeg-*amd64') && mv \"$FFMPEG_DIR/ffmpeg\" /usr/local/bin/",
  "chmod +x /usr/local/bin/ffmpeg"
]

[phases.build]
cmds = [
  "pnpm install",
  "pnpm build:deploy"
]

[start]
cmd = "cd packages/cli/bin && ./n8n"
