[build]
languages.node.version = "22.16.0"

[phases.setup]
nixPkgs = ["ffmpeg", "nodejs", "pnpm"]

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.start]
cmd = "cd packages/cli/bin && ./n8n"
