[phases.setup]
nixPkgs = ["nodejs", "ffmpeg", "corepack"]
# Enable corepack to use pnpm
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate"]

[phases.build]
cmds = ["pnpm install --frozen-lockfile", "pnpm build"]

[start]
cmd = "pnpm start"
