[phases.setup]
nixPkgs = [
  "nodejs_22",
  "pnpm"
]

cmds = [
  "curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz",
  "tar -xf ffmpeg.tar.xz",
  "mv ffmpeg-*-amd64/ffmpeg /usr/local/bin/",
  "chmod +x /usr/local/bin/ffmpeg"
]

[phases.build]
cmds = [
  "pnpm install",
  "pnpm build:deploy"
]

[start]
cmd = "cd packages/cli/bin && ./n8n"
