[phases.setup]
nixPkgs = ['nodejs_22', 'ffmpeg', 'yarn', 'python311']
cmds = [
  'yarn global add n8n'  # 👈 ensures CLI is available
]

[phases.build]
cmds = ['yarn install --immutable']

[phases.start]
cmd = 'n8n start'
