[phases.setup]
# Install system dependencies: Node.js and FFmpeg
nixPkgs = ["nodejs", "ffmpeg"]

[phases.build]
# Install dependencies and build your app
cmds = ["yarn install", "yarn build"]

[start]
# Run the app using Yarn's start script
cmd = "yarn start"
